### ISSUE TITLE
Newlines are not rendered when collapsed 

### ISSUE THREAD

**Issue by NimmLor** [fawaz-ahmed/react-native-read-more#26]
Also the text wraps up too soon

Code: 
```
<ReadMore
    numberOfLines={4}
    style={styles.description}
    seeMoreText="weiterlesen"
    seeLessText="weniger anzeigen"
    ellipsis="..."
    seeMoreStyle={{ color: theme.colors.primary }}
    seeLessStyle={{ color: theme.colors.primary }}
    >
        {newsItem.description?.replace(/\n/g, ' \n ')}
</ReadMore>
```

![WhatsApp Image 2021-03-18 at 07 08 40](https://user-images.githubusercontent.com/32486857/111581231-28e92680-87b9-11eb-9562-6018826826a7.jpeg)

![WhatsApp Image 2021-03-18 at 07 08 40 (1)](https://user-images.githubusercontent.com/32486857/111581237-2e467100-87b9-11eb-8375-d1c5ab474394.jpeg)

Currently I'm replacing all `\n` with a whitespace, to avoid that the text is even written together

(using version ^2.0.0)

**Comment by fawaz-ahmed** [comment]
@NimmLor I need more context on the issues you are trying to resolve. Can you answer these questions:
1_ Newlines are not rendered when collapsed -> does this mean when you're changing the text being passed it's not being shown in collapsed state ? If not, please explain further.
2_ Also the text wraps up too soon -> does this means the animation of collapsing is too quick ? if not please explain further.
3_ Currently I'm replacing all \n with a whitespace, to avoid that the text is even written together -> so right now I'm just removing all line breaks, maybe that's why you're seeing all text concatenated. Will replacing all line breaks with a space help you ?

Explaining a bit more, the text in the second image is your actual formatted text. If I use it straight away in the collapsed state then positioning of the `see more` will become more complex. Do you want this to be displayed in original formatting in collapsed state as well ? or that's fine ?

**Comment by NimmLor** [comment]
Here an example that is a bit more clear. The string contains newlines, however, when it is collapsed the newlines are just ignored and the words are just appended together. However, if it is expanded everything is beaving as it should

```
<ReadMore numberOfLines={4} style={styles.description}>
  {'1. Long text of First line, 123 Lorem ipsum ABCD\n\n' +
    '2. Second Line, should have a spacing line between first and this line Lorem ipsum Lorem ipsum Lorem ipsum\n' +
    '3. Third Line, uses just a single linebreak before'}
</ReadMore>
```
![image](https://user-images.githubusercontent.com/32486857/111882320-4aaefd00-89b5-11eb-95f0-d9f7912f293e.png)

2. In some occasions there are some weird gaps between the seeMoreText and the content. And sometimes there is some space unused on the right that could easily take in 1-2 more words.

![image](https://user-images.githubusercontent.com/32486857/111882616-c8bfd380-89b6-11eb-9ade-1027d50843a3.png)


3. I'm not even sure in which case it would be useful to have the linebreaks removed

Thanks in advance 👍🏻

**Comment by NimmLor** [comment]
Created a pull request to fix the issue with the linebreaks #27

**Comment by fawaz-ahmed** [comment]
@NimmLor there is one problem that I foresee with your PR. If you preserve the line breaks and the last line in collapsed state is occupying the full width. Then, see more might overlap the text. Can you please try this once and let me know ?
If that works fine, then I'll be happy to merge this.

**Comment by NimmLor** [comment]
It seems to be working fine for me

![ezgif-3-7bd654b1e47b](https://user-images.githubusercontent.com/32486857/111921205-920bbb00-8a93-11eb-9423-0f578de1ae5b.gif)

**Comment by fawaz-ahmed** [comment]
Looks good. Please update version in package.json to 2.0.1 and I'll merge it.
Thanks for helping Lorenz
________________________________

**Comment by NimmLor** [comment]
bumped the version and remove the console.log with the padding
